name: my_data_visualization_project  
channels:
  - conda-forge  
dependencies:
  - pandas  # For data manipulation
  - altair  # For data visualization
  - pandas
  - ipywidgets
  - jupyterlab
  - voila
